site_name: tqdm-tag
site_description: Color-code individual items in a tqdm progress bar by tagging them with a status.
site_url: https://tqdm-tag.readthedocs.io
repo_url: https://github.com/ColinMoldenhauer/tqdm-tag
repo_name: ColinMoldenhauer/tqdm-tag

docs_dir: docs

nav:
  - Home: index.md
  - API: api.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: teal

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            members_order: source
